server:
    port: 8080
    session:
      timeout: 10
      cookie:
        comment: test cookie comment

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/medical_history??useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
        username: paul
        password: wy806380634
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
    http:
      encoding:
        charset: utf-8

Token:
#  maxAge: 15000
#  SECRET: qwe123asd456zxc789t
#  signatureAlgorithm: SignatureAlgorithm.HS256