server:
    port: 8080

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/medical_history??useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true&zeroDateTimeBehavior=round
        username: paul
        password: wy806380634
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
    http:
      multipart:
        max-file-size: 100Mb

JwtSetting:
  max-age: 18000000 #5小时
  s-e-c-r-e-t: ou1218hw8houht11oub

